<?php
// All country name
global $countries;
$countries = array(
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
);

// General travel activities
global $activity_set;
$activity_set = array(
    'fa fa-binoculars' => 'Sightseeing',
    'fa fa-hiking' => 'Hiking',
    'fa fa-umbrella-beach' => 'Beach Relaxation',
    'fa fa-landmark' => 'Cultural Exploration',
    'fa fa-city' => 'City Tour',
    'fa fa-dumbbell' => 'Adventure Sports',
    'fa fa-paw' => 'Wildlife Safari',
    'fa fa-campground' => 'Camping',
    'fa fa-utensils' => 'Food Tasting',
    'fa fa-ship' => 'Boat Cruise',
    'fa fa-camera' => 'Photography',
    'fa fa-shopping-bag' => 'Shopping',
    'fa fa-spa' => 'Spa and Wellness',
    'fa fa-monument' => 'Historical Tours',
    'fa fa-swimming-pool' => 'Water Activities',
    'fa fa-tree' => 'Nature Walks',
    'fa fa-museum' => 'Museum Visits',
    'fa fa-wine-glass-alt' => 'Wine Tasting',
    'fa fa-glass-cheers' => 'Local Festivals',
    'fa fa-cocktail' => 'Nightlife',
    'fa fa-road' => 'Road Trip',
    'fa fa-hiking' => 'Trekking',
    'fa fa-water' => 'Scuba Diving',
    'fa fa-snorkel-mask' => 'Snorkeling',
    'fa fa-mountain' => 'Mountain Climbing',
    'fa fa-bicycle' => 'Cycling',
    'fa fa-yoga' => 'Yoga Retreat',
    'fa fa-shopping-basket' => 'Food Market Tour',
    'fa fa-sun' => 'Sunset Watching',
    'fa fa-rafting' => 'River Rafting',
    'fa fa-binoculars' => 'Bird Watching',
    'fa fa-paint-brush' => 'Art Galleries',
    'fa fa-utensils' => 'Cooking Classes',
    'fa fa-hands-helping' => 'Volunteering',
    'fa fa-parachute-box' => 'Parasailing',
    'fa fa-archway' => 'Archaeological Sites',
    'fa fa-sun' => 'Sunbathing',
    'fa fa-train' => 'Train Rides',
    'fa fa-ship' => 'Cruise Excursions',
    'fa fa-helicopter' => 'Helicopter Tours',
    'fa fa-exchange-alt' => 'Ziplining',
    'fa fa-surfing' => 'Surfing',
    'fa fa-kayak' => 'Kayaking',
    'fa fa-golf-ball' => 'Golfing',
    'fa fa-cave' => 'Spelunking',
    'fa fa-skiing' => 'Skiing',
    'fa fa-wind' => 'Windsurfing',
    'fa fa-caravan' => 'Desert Safari',
    'fa fa-motorcycle' => 'Motorbike Tours',
    'fa fa-parachute-box' => 'Skydiving',
    'fa fa-dolphin' => 'Dolphin Watching',
    'fa fa-utensils' => 'Local Cuisine Experience',
    'fa fa-monument' => 'Monument Visits',
    'fa fa-hot-air-balloon' => 'Hot Air Ballooning',
    'fa fa-palette' => 'Art and Craft Workshops',
    'fa fa-tree' => 'Gardens and Parks',
    'fa fa-cookie' => 'Snack Tasting',
    'fa fa-farm' => 'Farm Visits',
    'fa fa-waterfall' => 'Waterfall Exploration',
    'fa fa-helicopter' => 'Helicopter Sightseeing',
    'fa fa-motorcycle' => 'Motorcycle Tours',
    'fa fa-hat-cowboy' => 'Cultural Festivals',
    'fa fa-fish' => 'Fishing',
    'fa fa-canyon' => 'Canyoning',
    'fa fa-hiking' => 'Sunrise Trek',
    'fa fa-horse' => 'Horseback Riding',
    'fa fa-cave' => 'Caving',
    'fa fa-heart' => 'Honeymoon Specials',
    'fa fa-exchange-alt' => 'Zip-lining',
    'fa fa-mountain' => 'Glacier Hiking',
    'fa fa-theater-masks' => 'Cultural Shows',
    'fa fa-beer' => 'Beer Tasting',
    'fa fa-tea' => 'Tea Plantation Tours',
    'fa fa-ship' => 'River Cruises',
    'fa fa-fish' => 'Marine Life Encounters',
    'fa fa-utensils' => 'Cooking Experiences',
    'fa fa-bolt' => 'Bungee Jumping',
    'fa fa-campground' => 'Desert Camping',
    'fa fa-mountain' => 'Rock Climbing',
    'fa fa-camera' => 'Photography Tours',
    'fa fa-ship' => 'Boat Tours',
    'fa fa-sun' => 'Sunrise Watching',
    'fa fa-surfing' => 'Surf Lessons',
    'fa fa-elephant' => 'Elephant Sanctuaries',
    'fa fa-motorcycle' => 'Motorbike Rentals',
    'fa fa-paragliding' => 'Paragliding',
    'fa fa-yoga' => 'Yoga and Meditation Retreats',
    'fa fa-utensils' => 'Street Food Tours',
    'fa fa-mountain' => 'Ice Climbing',
    'fa fa-theater-masks' => 'Opera and Theater Shows',
    'fa fa-tree' => 'Nature Reserves',
    'fa fa-beer' => 'Beer Breweries',
    'fa fa-palette' => 'Art Museums',
    'fa fa-hiking' => 'Hiking Expeditions',
    'fa fa-wine-glass' => 'Winery Visits',
    'fa fa-shopping-basket' => 'Local Market Visits',
    'fa fa-ship' => 'Sailing Trips',
    'fa fa-hands-helping' => 'Cultural Workshops',
    'fa fa-snowboarding' => 'Snowboarding',
    'fa fa-paw' => 'Wildlife Encounters'
);